### ISSUE TITLE
Graph not showing with v9.11.4210

### ISSUE THREAD

**Issue by MarcelloTheArcane** [d-krupke/CP-SAT-Log-Analyzer#10] opened 2024-09-20 18:48 UTC
Hello

I'm not sure if it's just me, but it seems like the solver log is formatted slightly differently in v9.11.4210 (Python 3.8.10), which means graphs are no longer parsed correctly.

I've attached an example log: [urgent_sets_log.txt](https://github.com/user-attachments/files/17079756/urgent_sets_log.txt)

The offending line is:

```text
3 helper subsolvers: [neighborhood_helper, synchronization_agent, update_gap_integral]

#1       0.05s best:40    next:[39,39]    no_lp (fixed_bools=0/6)
```

If I remove the newline in between the two lines, the graph now shows correctly.

I'm not sure if there's any other whitespace differences that are hiding other graphs...

**Comment by d-krupke** [comment] 2024-09-20 23:06
Thanks for letting me know. I haven't made the switch yet but I will check it soon and fix it if necessary. Looks unfortunately more annoying to parse. 🤔

**Comment by d-krupke** [comment] 2024-09-21 07:57
I can confirm the bug with the new version.

**Comment by d-krupke** [comment] 2024-09-21 16:43
Should be fixed now. Not pretty but I unfortunately do not have the time to rewrite that part properly. I used the empty lines to separate the blocks and find the right parser for each, but this block now being split into two (but being a single block in older versions) requires a different handling. My current workaround is just to find and remove that specific empty line so the old blocks are restored.

**Closed by d-krupke** 2024-09-21 16:43 UTC
Labels: bug

**Comment by eyaler** [comment] 2024-10-12 13:29
@d-krupke i tried the log file provided in the [1st comment](https://github.com/d-krupke/CP-SAT-Log-Analyzer/issues/10#issue-2539456258), and i get:
```
Could not render block Search progress: of type <class 'cpsat_log_parser.blocks.search_progress.SearchProgressBlock'>. Error: '<class 'streamlit.errors.StreamlitDuplicateElementId'>' - 'There are multiple plotly_chart elements with the same auto-generated ID. When this element is created, it is assigned an internal ID based on the element type and provided parameters. Multiple elements with the same type and parameters will cause this error.

To fix this error, please pass a unique key argument to the plotly_chart element.'. Please check the raw log. If you think this is a bug, please report it [here](https://github.com/d-krupke/CP-SAT-Log-Analyzer/issues).
```
manually removed the newline suggested did not help.

**Comment by d-krupke** [comment] 2024-10-12 14:15
> @d-krupke i tried the log file provided in the [1st comment](https://github.com/d-krupke/CP-SAT-Log-Analyzer/issues/10#issue-2539456258), and i get:
> 
> ```
> 
> Could not render block Search progress: of type <class 'cpsat_log_parser.blocks.search_progress.SearchProgressBlock'>. Error: '<class 'streamlit.errors.StreamlitDuplicateElementId'>' - 'There are multiple plotly_chart elements with the same auto-generated ID. When this element is created, it is assigned an internal ID based on the element type and provided parameters. Multiple elements with the same type and parameters will cause this error.
> 
> 
> 
> To fix this error, please pass a unique key argument to the plotly_chart element.'. Please check the raw log. If you think this is a bug, please report it [here](https://github.com/d-krupke/CP-SAT-Log-Analyzer/issues).
> 
> ```
> 
> manually removed the newline suggested did not help.

That is odd. I will check and fix it later today. Thanks for letting me know. Seems to be an issue with plotly.

**Comment by d-krupke** [comment] 2024-10-12 14:53
Was able to reproduce the problem. Seems to be linked to an update of either streamlit or plotly. Will open a new issue.

**Comment by d-krupke** [comment] 2024-10-12 15:03
@eyaler it should be fixed now.
